# Generated by Django 5.0.8 on 2024-11-20 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0002_publicletter_feature_photo'),
    ]

    operations = [
    ]
