# Generated by Django 5.0.8 on 2024-12-07 11:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0004_blogpost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogInteraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_type', models.CharField(choices=[('view', 'View'), ('click', 'Click'), ('like', 'Like'), ('comment', 'Comment')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('public_letter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='vaultapp.publicletter')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blog_interactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
