# Generated by Django 5.0.8 on 2024-12-07 11:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0006_publicletter_view_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='letterreaction',
            unique_together={('public_letter', 'user')},
        ),
        migrations.AlterField(
            model_name='letterreaction',
            name='public_letter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='vaultapp.publicletter'),
        ),
        migrations.AlterField(
            model_name='letterreaction',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='letterreaction',
            name='reaction_type',
        ),
    ]
