# Generated by Django 5.0.8 on 2025-01-19 18:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vaultapp', '0010_blogview'),
        ('vaultapp', '0010_letter_priority'),
    ]

    operations = [
    ]
